pipeline:
  identifier: Build_sample_app_docker_1684253940922
  name: Build sample-app-docker
  orgIdentifier: default
  projectIdentifier: Vishsample
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1684246355606
        repoName: Vishnu-Harness/sample-app-docker
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: vish_con
                    repo: vishnuharness/sample
                    tags:
                      - test2
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
